# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 858f5ef5b0268b94bbe081014c8ff99bea171d42d09f8146bf6fbb84ce7f5917932278d68a7687dadd90e2000834dab05b4ee64c4e8551389de21d27644504c9

test:
  secret_key_base: 01dd21c39ede7595c79d7abd952931f61abb777adf0dceb815ae086f8d51a5aeb874c4a5cb4b9fe17766591e6e97305f0399200bc484c429b15d3906b23cb2a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
